# Generated by Django 3.2 on 2022-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('jakarta', 'Jakarta'), ('malang', 'Malang'), ('jambi', 'Jambi'), ('bali', 'Bali')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('with_note', 'With Note')], max_length=20)),
                ('barcode', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
