version: '3.1'

services:

    db:
        image: postgres:14.1-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
            POSTGRES_DB: db_backstage

    adminer:
        image: adminer:4.8.1-standalone
        ports:
            - 8080:8080

    redis:
        image: redis:6.2-alpine
        ports:
            - 6379:6379

    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - '8001:8001'
